import { GmailThreadGetResponse } from './thread';

// Request interface for AI search query generation
export interface GmailSearchQueryRequest {
  prompt: string;
}

// Individual search query generated by AI
export interface GmailSearchQuery {
  query: string;
  confidence: number;
  reasoning: string;
}

// Response interface for AI search query generation
export interface GmailSearchQueryResponse {
  query: string;
  description: string;
}

// Request interface for AI search with threads
export interface GmailSearchWithThreadsRequest {
  prompt: string;
  pageToken?: string;
  maxResults?: number;
}

// Response interface for AI search with threads
export interface GmailSearchWithThreadsResponse {
  generatedQueries: GmailSearchQuery[];
  selectedQuery: string;
  threads: GmailThreadGetResponse[];
  nextPageToken?: string;
}
