export const FCM_START_SERVICE = 'MESSAGE_RECEIVER:::FCM_START_SERVICE';
export const FCM_SERVICE_STARTED = 'MESSAGE_RECEIVER:::FCM_SERVICE_STARTED';
export const FCM_SERVICE_ERROR = 'MESSAGE_RECEIVER:::FCM_SERVICE_ERROR';
export const FCM_MESSAGE_RECEIVED = 'MESSAGE_RECEIVER:::FCM_MESSAGE_RECEIVED';
export const FCM_TOKEN_UPDATED = 'MESSAGE_RECEIVER:::FCM_TOKEN_UPDATED';
export const FCM_STOP_SERVICE = 'MESSAGE_RECEIVER:::FCM_STOP_SERVICE';
