#!/usr/bin/env node
/**
 * Local mock backend for monomail-desktop Phase B end-to-end testing.
 *
 * Implements the minimum surface defined in docs/ON_PREM_BACKEND_CONTRACT.md
 * so the desktop client can complete sign-in, refresh tokens, receive
 * pushes, and load past the login screen — without waiting on the real
 * backend team.
 *
 * Usage:
 *   node scripts/mock-backend.mjs              # listens on http://localhost:3030
 *   MOCK_BACKEND_PORT=8080 node scripts/mock-backend.mjs
 *
 * Then in .env (rebuild required — electron-vite bakes env at build time):
 *   MONO_ENV_HOMEPAGE_DOMAIN=http://localhost:3030
 *   MONO_ENV_API_URL=http://localhost:3030
 *   MONO_ENV_BACKEND_URL=http://localhost:3030
 *   MONO_ENV_PUBLIC_DOMAIN=http://localhost:3030
 */

import { createHmac, randomBytes } from 'crypto';
import { createServer } from 'http';
import { URL } from 'url';
import { WebSocketServer } from 'ws';

const PORT = Number(process.env.MOCK_BACKEND_PORT || 3030);
const DEEPLINK_PROTOCOL = process.env.MOCK_DEEPLINK_PROTOCOL || 'mono-desktop';
const TOKEN_TTL_SEC = Number(process.env.MOCK_TOKEN_TTL_SEC || 3600);
const PUSH_INTERVAL_MS = Number(process.env.MOCK_PUSH_INTERVAL_MS || 30_000);

// HMAC-signed JWT-shaped tokens. Not real JWT — just `header.payload.sig`
// so the client's basic shape validator accepts them. Keep the secret
// stable for the process lifetime so refresh tokens validate.
const SECRET = randomBytes(32).toString('hex');

const STUB_MEMBER = {
  uid: 'mock-member-1',
  displayName: 'Mock User',
  email: 'mock.user@example.com',
  primaryUid: 'mock-account-primary',
  memberName: 'mock.user',
  profileImageUrl: '',
  timezone: 'America/Los_Angeles',
  demographics: { role: '', emailUsage: '', discoverySource: '' },
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString()
};

const STUB_ACCOUNTS = [
  {
    uid: 'mock-account-primary',
    displayName: 'Mock User',
    provider: 'google',
    email: 'mock.user@example.com',
    profileImageUrl: '',
    primary: true,
    scopes: ['https://mail.google.com/', 'https://www.googleapis.com/auth/gmail.modify'],
    isExpired: false
  }
];
const accountLinkIntents = new Map();

// ---------- Stub inbox content ---------------------------------------------
// Without these, the inbox renders empty and exercising the snooze flow
// end-to-end is impossible (no thread rows to hover). Real backend would
// stream actual Gmail history; here we generate a small fixed set on
// boot so the renderer has something to display.

function makeStubThread(i, accountId) {
  const hoursAgo = i * 3 + 1;
  const ts = Date.now() - hoursAgo * 60 * 60 * 1000;
  const SENDERS = [
    { name: 'Alex Park', email: 'alex@design.example' },
    { name: 'Sam Wright', email: 'sam@vendor.example' },
    { name: 'Jamie Cohen', email: 'jamie@team.example' },
    { name: 'Morgan Lee', email: 'morgan@news.example' },
    { name: 'Riley Tan', email: 'riley@personal.example' },
    { name: 'Drew Patel', email: 'drew@product.example' },
    { name: 'Casey Kim', email: 'casey@ops.example' },
    { name: 'Avery Ross', email: 'avery@support.example' }
  ];
  const SUBJECTS = [
    'Q3 design review notes',
    'Re: contract draft v2',
    'Lunch Thursday?',
    'Weekly product digest',
    'Reservation confirmed',
    'Roadmap sync — agenda',
    'Server alert: latency spike',
    'Welcome to the platform'
  ];
  const SNIPPETS = [
    "Wanted to recap what we agreed on yesterday. The hero section should…",
    "Attaching the revised contract — call out anything that doesn't track.",
    "Quick one — are you around for lunch on Thursday? Trying that new place.",
    "Top stories this week: incident retrospective, mobile beta numbers…",
    "Your reservation for Saturday is confirmed. We'll see you at 7pm.",
    "Here's the proposed agenda for tomorrow's sync. Add anything I missed.",
    "We detected elevated p95 latency on the API. Investigation thread inside.",
    'Thanks for joining! Here are a few links to get you started.'
  ];
  const sender = SENDERS[i % SENDERS.length];
  const subject = SUBJECTS[i % SUBJECTS.length];
  const snippet = SNIPPETS[i % SNIPPETS.length];
  const threadId = `mock-thread-${i + 1}`;
  const recipient = { name: 'Mock User', email: STUB_MEMBER.email };
  const message = {
    id: `mock-msg-${i + 1}-1`,
    timestamp: ts,
    author: sender,
    type: 'message',
    timezone: 'UTC',
    threadId,
    subject,
    labelIds: ['INBOX', i % 3 === 0 ? 'UNREAD' : ''].filter(Boolean),
    snippet,
    historyId: String(1000 + i),
    cc: [],
    bcc: [],
    to: [recipient],
    from: sender,
    listUnsubscribe: { url: [], mailTo: [] },
    inlineImageSize: 0,
    inlineImages: {},
    attachments: {},
    payload: {
      partId: '',
      mimeType: 'text/plain',
      fileName: '',
      body: { attachmentId: null, size: snippet.length, data: null }
    },
    bodyPlain: `${snippet}\n\n(This is a stub message generated by mock-backend.mjs.)`,
    bodyHtml: `<p>${snippet}</p><p><em>(This is a stub message generated by mock-backend.mjs.)</em></p>`
  };
  return {
    id: threadId,
    accountId,
    historyId: String(1000 + i),
    labelIds: message.labelIds,
    attachments: {},
    from: [sender],
    to: [recipient],
    cc: [],
    bcc: [],
    subject,
    snippet,
    timestamp: ts,
    items: [message]
  };
}

const STUB_THREADS = Array.from({ length: 8 }, (_, i) =>
  makeStubThread(i, 'mock-account-primary')
);
const STUB_THREADS_BY_ID = new Map(STUB_THREADS.map((t) => [t.id, t]));

const STUB_PREFERENCE = {
  language: 'en',
  appearance: { theme: 'system', density: 'cozy' },
  compose: { cancelWindow: 5, fullscreen: false },
  account: { accentColor: {} },
  signature: { includeInReplies: true, includeInForwards: true, includeInNewMessages: true },
  display: { inbox: { category: {} }, threadList: {} },
  notifications: {}
};

// ---------- P8 Later Queue ---------------------------------------------------
// In-memory storage of snoozed threads + scheduled drafts. Server is the
// source of truth in production; here it's a Map per type. Connected
// WebSocket clients (`wsClients`) receive THREAD_UNSNOOZED /
// SCHEDULED_SENT broadcasts when items fire on the queue tick (every 30s).

/** @type {Map<string, any>} */
const snoozes = new Map();
/** @type {Map<string, any>} */
const schedules = new Map();
/** @type {Map<string, any>} */
const mockSpaces = new Map();
/** @type {Set<import('ws').WebSocket>} */
const wsClients = new Set();

const QUEUE_MAX_PER_ACCOUNT = Number(process.env.MOCK_QUEUE_MAX_PER_ACCOUNT || 50);
// 60s in production; integration tests override to a much smaller window
// so reschedule + tick assertions don't have to wait a full minute. The
// invariant stays: timestamps must be in the future by at least this
// margin.
const QUEUE_MIN_FUTURE_MS = Number(process.env.MOCK_QUEUE_MIN_FUTURE_MS || 60_000);
const QUEUE_TICK_MS = Number(process.env.MOCK_QUEUE_TICK_MS || 30_000);

function isPlausibleIsoFuture(s) {
  if (typeof s !== 'string' || s.length === 0) return false;
  const t = Date.parse(s);
  if (Number.isNaN(t)) return false;
  return t - Date.now() >= QUEUE_MIN_FUTURE_MS;
}

function countByAccount(map, accountId) {
  let n = 0;
  for (const v of map.values()) if (v.accountId === accountId) n++;
  return n;
}

function broadcastQueueEvent(eventType, payload) {
  const frame = {
    data: { type: eventType, ...payload }
  };
  const json = JSON.stringify(frame);
  for (const ws of wsClients) {
    if (ws.readyState === ws.OPEN) {
      try {
        ws.send(json);
      } catch (e) {
        console.warn('[push] broadcast failed:', e.message);
      }
    }
  }
}

// ---------- token helpers ---------------------------------------------------

function base64url(buf) {
  return Buffer.from(buf)
    .toString('base64')
    .replace(/=+$/, '')
    .replace(/\+/g, '-')
    .replace(/\//g, '_');
}

function sign(payload) {
  const header = base64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = base64url(JSON.stringify(payload));
  const sig = base64url(createHmac('sha256', SECRET).update(`${header}.${body}`).digest());
  return `${header}.${body}.${sig}`;
}

function issueTokens() {
  const now = Math.floor(Date.now() / 1000);
  const accessToken = sign({
    sub: STUB_MEMBER.uid,
    email: STUB_MEMBER.email,
    iat: now,
    exp: now + TOKEN_TTL_SEC,
    type: 'access'
  });
  const refreshToken = sign({
    sub: STUB_MEMBER.uid,
    iat: now,
    exp: now + 86400 * 30,
    type: 'refresh',
    jti: randomBytes(8).toString('hex')
  });
  return { accessToken, refreshToken, expiresIn: TOKEN_TTL_SEC };
}

function ensureSecondaryAccount() {
  const existing = STUB_ACCOUNTS.find((account) => account.uid === 'mock-account-secondary');
  if (existing) return existing;

  const account = {
    uid: 'mock-account-secondary',
    displayName: 'Mock Secondary',
    provider: 'google',
    email: 'mock.secondary@gmail.com',
    profileImageUrl: '',
    primary: false,
    scopes: ['https://mail.google.com/', 'https://www.googleapis.com/auth/gmail.modify'],
    isExpired: false
  };
  STUB_ACCOUNTS.push(account);
  return account;
}

// ---------- request helpers -------------------------------------------------

function send(res, status, body, headers = {}) {
  const isJson = typeof body === 'object' && body !== null && !(body instanceof Buffer);
  const payload = isJson ? JSON.stringify(body) : body || '';
  res.writeHead(status, {
    'Content-Type': isJson ? 'application/json; charset=utf-8' : 'text/html; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': '*',
    'Access-Control-Allow-Methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS',
    ...headers
  });
  res.end(payload);
}

async function readJson(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      if (!raw) return resolve({});
      try {
        resolve(JSON.parse(raw));
      } catch (e) {
        reject(e);
      }
    });
    req.on('error', reject);
  });
}

// ---------- HTTP routes -----------------------------------------------------

const server = createServer(async (req, res) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const path = url.pathname.replace(/\/+$/, '') || '/';
  const method = req.method?.toUpperCase() ?? 'GET';

  if (method === 'OPTIONS') return send(res, 204, '');

  console.log(`[mock] ${method} ${path}${url.search}`);

  // --- Sign-in page ---
  if (method === 'GET' && path === '/sign-in') {
    const tokens = issueTokens();
    const deeplink = `${DEEPLINK_PROTOCOL}://signIn?token=${encodeURIComponent(
      tokens.accessToken
    )}&refresh_token=${encodeURIComponent(tokens.refreshToken)}&expires_in=${tokens.expiresIn}`;
    return send(
      res,
      200,
      `<!doctype html>
<html>
<head>
  <title>Mock Sign In</title>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 480px; margin: 80px auto; padding: 24px; }
    h1 { font-size: 22px; letter-spacing: -0.01em; }
    p { color: #666; line-height: 1.5; }
    code { background: #f5f5f5; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
    .btn { display: inline-block; padding: 10px 18px; background: #dc2626; color: #fff; border: none; border-radius: 6px; text-decoration: none; cursor: pointer; font-size: 14px; }
    .btn:hover { background: #b91c1c; }
    .small { font-size: 12px; color: #999; margin-top: 32px; }
  </style>
</head>
<body>
  <h1>Mock backend sign-in</h1>
  <p>This is the local <code>mock-backend</code> standing in for your on-prem sign-in page. Clicking below issues stub access + refresh tokens and redirects back to the desktop app via <code>${DEEPLINK_PROTOCOL}://</code>.</p>
  <a class="btn" href="${deeplink}">Continue as ${STUB_MEMBER.email}</a>
  <p class="small">Tokens last ${TOKEN_TTL_SEC}s. The client will refresh automatically via <code>POST /auth/refresh</code>.</p>
</body>
</html>`
    );
  }

  if (method === 'POST' && path === '/desktop/account-link-intents') {
    const body = await readJson(req).catch(() => ({}));
    const provider = typeof body.provider === 'string' ? body.provider : 'gmail';
    if (provider !== 'gmail') {
      return send(res, 400, {
        error: `Provider "${provider}" is not supported by the mock backend`
      });
    }

    const intent = `mock-intent-${randomBytes(18).toString('hex')}`;
    const expiresAt = new Date(Date.now() + 10 * 60_000).toISOString();
    accountLinkIntents.set(intent, {
      provider,
      expiresAt,
      completionCode: null,
      completionExpiresAt: null,
      used: false
    });
    return send(res, 200, { intent, expiresAt });
  }

  if (method === 'GET' && path === '/add-account') {
    const intent = url.searchParams.get('intent');
    const entry = intent ? accountLinkIntents.get(intent) : null;
    if (intent && (!entry || entry.used || Date.parse(entry.expiresAt) <= Date.now())) {
      return send(
        res,
        400,
        '<!doctype html><html><body><h1>Mock add account failed</h1><p>The account-link intent is invalid or expired.</p></body></html>'
      );
    }

    const completionCode = `mock-link-code-${randomBytes(18).toString('hex')}`;
    if (entry) {
      entry.completionCode = completionCode;
      entry.completionExpiresAt = new Date(Date.now() + 5 * 60_000).toISOString();
    }
    const account = ensureSecondaryAccount();
    const deeplink = `${DEEPLINK_PROTOCOL}://addAccount?intent=${encodeURIComponent(
      intent || ''
    )}&code=${encodeURIComponent(completionCode)}`;
    return send(
      res,
      200,
      `<!doctype html>
<html>
<head>
  <title>Mock Add Gmail</title>
  <meta charset="utf-8" />
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 480px; margin: 80px auto; padding: 24px; }
    h1 { font-size: 22px; letter-spacing: -0.01em; }
    p { color: #666; line-height: 1.5; }
    code { background: #f5f5f5; padding: 2px 6px; border-radius: 4px; font-size: 13px; }
    .btn { display: inline-block; padding: 10px 18px; background: #dc2626; color: #fff; border: none; border-radius: 6px; text-decoration: none; cursor: pointer; font-size: 14px; }
    .btn:hover { background: #b91c1c; }
    .small { font-size: 12px; color: #999; margin-top: 32px; }
  </style>
</head>
<body>
  <h1>Mock Gmail account link</h1>
  <p>This simulates completing Google OAuth and linking <code>${account.email}</code> to the current desktop session.</p>
  <a class="btn" href="${deeplink}">Return to Mono Mail</a>
  <p class="small">The desktop app opened this page with an opaque account-link intent, not a bearer token.</p>
</body>
  </html>`
    );
  }

  if (method === 'POST' && path === '/desktop/account-link-completions') {
    const body = await readJson(req).catch(() => ({}));
    const intent = typeof body.intent === 'string' ? body.intent : '';
    const code = typeof body.code === 'string' ? body.code : '';
    const entry = intent ? accountLinkIntents.get(intent) : null;

    if (
      !entry ||
      entry.used ||
      Date.parse(entry.expiresAt) <= Date.now() ||
      !entry.completionCode ||
      entry.completionCode !== code ||
      !entry.completionExpiresAt ||
      Date.parse(entry.completionExpiresAt) <= Date.now()
    ) {
      return send(res, 400, {
        error: 'Account-link completion code is invalid or expired'
      });
    }

    entry.used = true;
    ensureSecondaryAccount();
    return send(res, 200, issueTokens());
  }

  if (method === 'POST' && path === '/desktop/unsubscribe') {
    const body = await readJson(req).catch(() => ({}));
    const unsubscribeUrl = typeof body.url === 'string' ? body.url : '';
    try {
      const parsed = new URL(unsubscribeUrl);
      if (parsed.protocol !== 'https:') {
        return send(res, 400, { ok: false, error: 'Only HTTPS unsubscribe URLs are allowed' });
      }
    } catch {
      return send(res, 400, { ok: false, error: 'Invalid unsubscribe URL' });
    }

    // Production should perform the outbound List-Unsubscribe request here.
    // The mock does not contact external hosts; it only proves the desktop
    // sends sender-controlled URLs to the backend proxy instead of fetching
    // them directly from the user's machine.
    return send(res, 200, { ok: true, status: 204 });
  }

  // --- Auth refresh ---
  if (method === 'POST' && path === '/auth/refresh') {
    try {
      const body = await readJson(req);
      if (!body.refreshToken || typeof body.refreshToken !== 'string') {
        return send(res, 400, { error: 'refreshToken required' });
      }
      // Mock backend doesn't validate the signature — any non-empty string
      // refreshes successfully. Real backend should verify HMAC + jti.
      return send(res, 200, issueTokens());
    } catch (e) {
      return send(res, 400, { error: 'bad json' });
    }
  }

  // --- NPS (ported Cloud Function) ---
  if (method === 'GET' && path === '/nps/entries') {
    return send(res, 200, { entries: [], totalCount: 0 });
  }
  if (method === 'POST' && path === '/nps') {
    const body = await readJson(req).catch(() => ({}));
    const entry = {
      id: randomBytes(6).toString('hex'),
      score: body.score ?? 0,
      comment: body.comment ?? '',
      userEmail: STUB_MEMBER.email,
      eventType: body.eventType ?? 'general_feedback',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      userId: STUB_MEMBER.uid
    };
    return send(res, 200, entry);
  }

  // --- Share resolver (placeholder) ---
  if (method === 'GET' && path.startsWith('/share/')) {
    return send(
      res,
      200,
      '<html><body><h1>Mock share view</h1><p>This would resolve a share token to the actual content in the real backend.</p></body></html>'
    );
  }

  // --- Mono REST API (mounted under /api/v1) ---
  if (path.startsWith('/api/v1/')) {
    const apiPath = path.slice('/api/v1'.length);

    if (method === 'GET' && apiPath === '/mono/user/info') {
      return send(res, 200, {
        member: STUB_MEMBER,
        accounts: STUB_ACCOUNTS,
        relatedMembers: []
      });
    }
    if (method === 'POST' && apiPath === '/mono/user/create') {
      return send(res, 200, {
        member: STUB_MEMBER,
        accounts: STUB_ACCOUNTS,
        relatedMembers: []
      });
    }
    if (method === 'GET' && apiPath === '/mono/preference') {
      return send(res, 200, STUB_PREFERENCE);
    }
    if (method === 'PATCH' && apiPath === '/mono/preference') {
      const body = await readJson(req).catch(() => ({}));
      return send(res, 200, { ...STUB_PREFERENCE, ...(body.preference ?? {}) });
    }

    // /mail/threads/:id — single thread fetch (e.g. when the user opens
    // a thread in the reader). Must come before the list match below
    // because the list path is `/mail/threads?q=…` which also starts
    // with `/mail/threads`.
    {
      const m = apiPath.match(/^\/mail\/threads\/([^/]+)$/);
      if (m && method === 'GET') {
        const id = decodeURIComponent(m[1]);
        const thread = STUB_THREADS_BY_ID.get(id);
        if (!thread) return send(res, 404, { error: 'thread not found' });
        return send(res, 200, thread);
      }
      // Modify/batch-modify routes return void; the unstubbed catch-all
      // already handles them. Leaving here so future changes are
      // intentional.
    }

    if (method === 'GET' && apiPath.startsWith('/mail/threads')) {
      // Ignore filter `q` for the mock — return all stub threads
      // regardless of query so every inbox view has content. Real
      // backend honors `category:primary`, `is:starred`, etc.
      return send(res, 200, {
        threads: STUB_THREADS,
        nextPageToken: null,
        resultSizeEstimate: STUB_THREADS.length
      });
    }
    if (method === 'GET' && apiPath === '/mail/drafts') {
      return send(res, 200, { drafts: [], nextPageToken: null });
    }
    if (method === 'GET' && apiPath.startsWith('/label')) {
      return send(res, 200, { labels: [] });
    }
    if (method === 'GET' && (apiPath === '/mono/spaces' || apiPath === '/spaces')) {
      return send(res, 200, Array.from(mockSpaces.values()));
    }
    if (method === 'POST' && apiPath === '/mono/spaces') {
      const body = await readJson(req).catch(() => ({}));
      const id = `space-${randomBytes(4).toString('hex')}`;
      const space = {
        id,
        name: body.name || 'My Space',
        color: body.color || '#4f46e5',
        icon: body.icon || '🏠',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        pinnedEmails: [],
        accountUids: body.accountUids || STUB_ACCOUNTS.map((a) => a.uid),
        default: mockSpaces.size === 0
      };
      mockSpaces.set(id, space);
      return send(res, 200, space);
    }
    if (method === 'GET' && apiPath.startsWith('/mono/spaces/')) {
      const id = apiPath.split('/')[3];
      const space = mockSpaces.get(id);
      if (!space) return send(res, 404, { error: 'Space not found' });
      return send(res, 200, space);
    }
    if (method === 'PATCH' && apiPath.startsWith('/mono/spaces/')) {
      const id = apiPath.split('/')[3];
      const existing = mockSpaces.get(id);
      if (!existing) return send(res, 404, { error: 'Space not found' });
      const body = await readJson(req).catch(() => ({}));
      const updated = { ...existing, ...body, id, updatedAt: new Date().toISOString() };
      mockSpaces.set(id, updated);
      return send(res, 200, updated);
    }
    if (method === 'GET' && apiPath.startsWith('/mono/contact')) {
      return send(res, 200, { contacts: [] });
    }
    if (method === 'GET' && apiPath.startsWith('/mono/share')) {
      return send(res, 200, {});
    }
    if (method === 'GET' && apiPath.startsWith('/mono/pin')) {
      return send(res, 200, { pinnedEmails: [] });
    }
    if (method === 'GET' && apiPath.startsWith('/mono/bookmark')) {
      return send(res, 200, { bookmarks: [], total: 0 });
    }
    if (method === 'GET' && apiPath.startsWith('/mono/signature')) {
      return send(res, 200, []);
    }
    if (method === 'GET' && apiPath.startsWith('/mono/template')) {
      return send(res, 200, []);
    }
    if (method === 'GET' && apiPath.startsWith('/track/')) {
      return send(res, 200, { events: [], histories: [] });
    }
    if (method === 'GET' && apiPath.startsWith('/mail/label')) {
      return send(res, 200, { labels: [] });
    }
    if (method === 'GET' && apiPath.startsWith('/ai-filter')) {
      return send(res, 200, { filters: [] });
    }
    if (method === 'POST' && apiPath === '/gmail/watch') {
      return send(res, 200, { historyId: '0', expiration: String(Date.now() + 86400_000) });
    }
    if (method === 'POST' && apiPath.startsWith('/gmail/stop')) {
      return send(res, 200, {});
    }
    if (method === 'POST' && apiPath === '/mail/watch') {
      return send(res, 200, { ok: true });
    }

    // ---------- P8 Later Queue endpoints ----------------------------------

    // POST /mail/snooze — create snooze
    if (method === 'POST' && apiPath === '/mail/snooze') {
      const body = await readJson(req).catch(() => ({}));
      const { threadId, accountId, snoozeUntil } = body;
      if (!threadId || !accountId) {
        return send(res, 400, { error: 'threadId and accountId required' });
      }
      if (!isPlausibleIsoFuture(snoozeUntil)) {
        return send(res, 400, { error: 'snoozeUntil must be ISO8601 and ≥ 60s in the future' });
      }
      if (countByAccount(snoozes, accountId) >= QUEUE_MAX_PER_ACCOUNT) {
        return send(res, 402, { error: `quota exceeded (max ${QUEUE_MAX_PER_ACCOUNT})` });
      }
      // Reject duplicate active snooze for the same thread.
      for (const v of snoozes.values()) {
        if (v.threadId === threadId && v.accountId === accountId) {
          return send(res, 409, { error: 'thread already snoozed', snoozeId: v.snoozeId });
        }
      }
      const snoozeId = `snz-${randomBytes(6).toString('hex')}`;
      const record = {
        snoozeId,
        threadId,
        accountId,
        snoozeUntil,
        createdAt: new Date().toISOString(),
        // The thread snapshot is stubbed in dev — real backend pulls it
        // from the actual thread row.
        threadSnapshot: body.threadSnapshot ?? {
          subject: 'Mock thread',
          snippet: 'Mock snippet — real backend would populate this from the thread row.',
          from: { id: 'mock-sender', name: 'Mock Sender', email: 'mock@example.com' },
          isStarred: false
        }
      };
      snoozes.set(snoozeId, record);
      return send(res, 201, record);
    }

    // GET /mail/snooze — list snoozes for an account
    if (method === 'GET' && apiPath === '/mail/snooze') {
      const accountId = url.searchParams.get('accountId');
      const items = [];
      for (const v of snoozes.values()) {
        if (!accountId || v.accountId === accountId) items.push(v);
      }
      return send(res, 200, { items });
    }

    // DELETE /mail/snooze/:id — unsnooze now
    {
      const m = apiPath.match(/^\/mail\/snooze\/([^/]+)$/);
      if (m && method === 'DELETE') {
        const id = m[1];
        if (!snoozes.has(id)) return send(res, 404, { error: 'snooze not found' });
        snoozes.delete(id);
        // Notify clients so any open inbox view can refresh.
        broadcastQueueEvent('THREAD_UNSNOOZED', {
          snoozeId: id,
          threadId: (snoozes.get(id) ?? {}).threadId,
          accountId: (snoozes.get(id) ?? {}).accountId
        });
        return send(res, 200, { ok: true });
      }
      if (m && method === 'PATCH') {
        const id = m[1];
        if (!snoozes.has(id)) return send(res, 404, { error: 'snooze not found' });
        const body = await readJson(req).catch(() => ({}));
        if (!isPlausibleIsoFuture(body.snoozeUntil)) {
          return send(res, 400, { error: 'snoozeUntil must be ISO8601 and ≥ 60s in the future' });
        }
        const updated = { ...snoozes.get(id), snoozeUntil: body.snoozeUntil };
        snoozes.set(id, updated);
        broadcastQueueEvent('SNOOZE_RESCHEDULED', {
          snoozeId: id,
          snoozeUntil: body.snoozeUntil
        });
        return send(res, 200, updated);
      }
    }

    // POST /mail/schedule — schedule a draft
    if (method === 'POST' && apiPath === '/mail/schedule') {
      const body = await readJson(req).catch(() => ({}));
      const { draftId, sendAt, accountId } = body;
      if (!draftId || !accountId) {
        return send(res, 400, { error: 'draftId and accountId required' });
      }
      if (!isPlausibleIsoFuture(sendAt)) {
        return send(res, 400, { error: 'sendAt must be ISO8601 and ≥ 60s in the future' });
      }
      if (countByAccount(schedules, accountId) >= QUEUE_MAX_PER_ACCOUNT) {
        return send(res, 402, { error: `quota exceeded (max ${QUEUE_MAX_PER_ACCOUNT})` });
      }
      const scheduleId = `sch-${randomBytes(6).toString('hex')}`;
      const record = {
        scheduleId,
        draftId,
        accountId,
        sendAt,
        createdAt: new Date().toISOString(),
        draftSnapshot: body.draftSnapshot ?? {
          subject: 'Mock scheduled draft',
          bodySnippet: 'Mock body — real backend would populate from the draft row.',
          recipients: [],
          attachmentCount: 0,
          isReply: false
        }
      };
      schedules.set(scheduleId, record);
      return send(res, 201, record);
    }

    // GET /mail/schedule — list scheduled drafts
    if (method === 'GET' && apiPath === '/mail/schedule') {
      const accountId = url.searchParams.get('accountId');
      const items = [];
      for (const v of schedules.values()) {
        if (!accountId || v.accountId === accountId) items.push(v);
      }
      return send(res, 200, { items });
    }

    // /mail/schedule/:id and /mail/schedule/:id/send-now
    {
      const sendNowMatch = apiPath.match(/^\/mail\/schedule\/([^/]+)\/send-now$/);
      if (sendNowMatch && method === 'POST') {
        const id = sendNowMatch[1];
        const record = schedules.get(id);
        if (!record) return send(res, 404, { error: 'schedule not found' });
        schedules.delete(id);
        const messageId = `msg-${randomBytes(6).toString('hex')}`;
        broadcastQueueEvent('SCHEDULED_SENT', {
          scheduleId: id,
          draftId: record.draftId,
          accountId: record.accountId,
          messageId
        });
        return send(res, 200, { ok: true, messageId });
      }
      const m = apiPath.match(/^\/mail\/schedule\/([^/]+)$/);
      if (m && method === 'DELETE') {
        const id = m[1];
        if (!schedules.has(id)) return send(res, 404, { error: 'schedule not found' });
        schedules.delete(id);
        return send(res, 200, { ok: true });
      }
      if (m && method === 'PATCH') {
        const id = m[1];
        if (!schedules.has(id)) return send(res, 404, { error: 'schedule not found' });
        const body = await readJson(req).catch(() => ({}));
        if (!isPlausibleIsoFuture(body.sendAt)) {
          return send(res, 400, { error: 'sendAt must be ISO8601 and ≥ 60s in the future' });
        }
        const updated = { ...schedules.get(id), sendAt: body.sendAt };
        schedules.set(id, updated);
        broadcastQueueEvent('SCHEDULE_RESCHEDULED', { scheduleId: id, sendAt: body.sendAt });
        return send(res, 200, updated);
      }
    }

    // Everything else: pretend it's fine but log loudly so we know what
    // else the client wants.
    console.warn(`[mock] unstubbed ${method} ${path} → returning empty 200`);
    return send(res, 200, {});
  }

  return send(res, 404, { error: 'not found', path });
});

// ---------- WebSocket push --------------------------------------------------

const wss = new WebSocketServer({ server, path: '/push/ws' });

wss.on('connection', (ws, req) => {
  const url = new URL(req.url, `http://localhost:${PORT}`);
  const token = url.searchParams.get('token');
  if (!token) {
    console.log('[push] rejecting connection — no token');
    ws.close(4401, 'missing token');
    return;
  }
  console.log(`[push] client connected (token=${token.slice(0, 16)}…)`);
  wsClients.add(ws);

  // Send a welcome control frame (no `data` → client treats as control,
  // doesn't forward to renderer).
  ws.send(JSON.stringify({ type: 'hello', ts: Date.now() }));

  const interval = setInterval(() => {
    if (ws.readyState !== ws.OPEN) return;
    // Periodic test push — a fake "new message" event so you can watch
    // the renderer side react.
    const frame = {
      data: {
        type: 'MESSAGE_ADDED',
        aAUid: STUB_ACCOUNTS[0].uid,
        threadId: `mock-thread-${randomBytes(4).toString('hex')}`,
        id: `mock-msg-${randomBytes(4).toString('hex')}`,
        labels: '[INBOX, UNREAD]',
        verification: 'false',
        link: '',
        code: ''
      },
      notification: {
        title: 'Mock Sender <noreply@example.com>',
        body: 'This is a mock push to verify the WebSocket → renderer path.'
      }
    };
    try {
      ws.send(JSON.stringify(frame));
      console.log('[push] sent test MESSAGE_ADDED frame');
    } catch (e) {
      console.warn('[push] send failed:', e.message);
    }
  }, PUSH_INTERVAL_MS);

  ws.on('close', (code, reason) => {
    clearInterval(interval);
    wsClients.delete(ws);
    console.log(`[push] client closed code=${code} reason=${reason?.toString() || ''}`);
  });
  ws.on('error', (err) => console.warn('[push] error:', err.message));
});

// ---------- P8 piece 6: queue fire-time tick --------------------------------
// Iterates snoozes + schedules every QUEUE_TICK_MS. For any item whose
// time has passed, fires the corresponding push event to all connected
// clients and removes it from the map. Real backend would also actually
// send the email for SCHEDULED_SENT.

setInterval(() => {
  const now = Date.now();
  for (const [id, record] of snoozes) {
    if (Date.parse(record.snoozeUntil) <= now) {
      snoozes.delete(id);
      broadcastQueueEvent('THREAD_UNSNOOZED', {
        snoozeId: id,
        threadId: record.threadId,
        accountId: record.accountId
      });
      console.log(`[queue] fired THREAD_UNSNOOZED for ${id}`);
    }
  }
  for (const [id, record] of schedules) {
    if (Date.parse(record.sendAt) <= now) {
      schedules.delete(id);
      const messageId = `msg-${randomBytes(6).toString('hex')}`;
      broadcastQueueEvent('SCHEDULED_SENT', {
        scheduleId: id,
        draftId: record.draftId,
        accountId: record.accountId,
        messageId
      });
      console.log(`[queue] fired SCHEDULED_SENT for ${id} (msg=${messageId})`);
    }
  }
}, QUEUE_TICK_MS);

// ---------- Boot ------------------------------------------------------------

server.listen(PORT, () => {
  console.log(`\nMock backend listening on http://localhost:${PORT}`);
  console.log(`  Sign-in page:   http://localhost:${PORT}/sign-in`);
  console.log(`  Refresh:        POST http://localhost:${PORT}/auth/refresh`);
  console.log(`  Push WS:        ws://localhost:${PORT}/push/ws?token=…`);
  console.log(`  API base:       http://localhost:${PORT}/api/v1/…`);
  console.log('\nSet your .env to point at this host:');
  console.log('  MONO_ENV_HOMEPAGE_DOMAIN=http://localhost:' + PORT);
  console.log('  MONO_ENV_API_URL=http://localhost:' + PORT);
  console.log('  MONO_ENV_BACKEND_URL=http://localhost:' + PORT);
  console.log('  MONO_ENV_PUBLIC_DOMAIN=http://localhost:' + PORT);
  console.log('\nElectron-vite bakes env at build time — rebuild after editing .env.\n');
});
